logging:
  level: INFO

apify:
  api_token: ${APIFY_API_TOKEN}

instagram:
  accounts:
    - sanykorea

youtube:
  api_key: ${YOUTUBE_API_KEY}
  handles:
    - "@SANYKorea_1989"

output:
  # raw_path: data/raw
  # csv_path: data/processed
  # processed_path: data/processed
  data_path: data

mail:
  smtp_server: smtp.gmail.com
  smtp_port: 587
