logging:
  level: INFO
  file: logs/social_media_analytics.log

instagram:
  accounts:
    - sanykorea

youtube:
  handles:
    - "@SANYKorea_1989"

output:
  data_path: data

mail:
  smtp_server: smtp.gmail.com
  smtp_port: 587

setup:
  links:
    apify: https://console.apify.com/account/integrations
    youtube_api: https://console.cloud.google.com/apis/credentials
    smtp_password: https://myaccount.google.com/apppasswords