instagram:
  accounts:
    # - instagram
    - sanykorea

apify:
  api_token: ${APIFY_API_TOKEN}

youtube:
  api_key: ${YOUTUBE_API_KEY}
  handles:
    - "@SANYKorea_1989"

output:
  raw_path: data/raw
  csv_path: data/processed

logging:
  level: INFO